server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "${LAVALINK_PASSWORD:youshallnotpass}"
    bufferDurationMs: 1000
    frameBufferDurationMs: 1000
    # Tắt hoàn toàn plugin youtube có sẵn của Lavalink để tránh bị crash
    youtubeSearchEnabled: false
    sources:
      youtube: false  # TẮT YOUTUBE ĐỂ TRÁNH LỖI IP
      bandcamp: true
      soundcloud: true # BẬT SOUNDCLOUD
      twitch: true
      vimeo: true
      http: true
      local: false

# Nếu đang dùng plugin Youtube bên ngoài, cũng phải vô hiệu hóa nó
plugins:
  youtube:
    enabled: false # TẮT PLUGIN YOUTUBE

logging:
  file:
    max-size: 1GB
    path: ./logs/

  level:
    root: INFO
